# Use kubiya/base-action-store:stable as the base image.
# This image provides a pre-configured environment for action stores.
FROM kubiya/base-action-store:stable

# Set the working directory to /home/app within the container.
# This directory will contain all the necessary code and files.
WORKDIR /home/app

# Copy the requirements.txt file into the 'function/' directory in the container.
# The requirements.txt should list all Python packages needed for your action store.
COPY requirements.txt function/

# Install the Python packages listed in requirements.txt.
# The '--no-cache' flag ensures that the packages are installed fresh without using any cached versions.
# The '--user' flag installs the packages for the current user, avoiding the need for root permissions.
RUN pip install --no-cache -r function/requirements.txt --user

# Copy all the other source code and files into the 'function/' directory in the container.
# This is to ensure that all your action store code and additional files are present within the container.
COPY . function/

# Optional Overrides
# Uncomment the following lines if you want to override default settings from the base image.

# To override the default entrypoint:
# ENV fprocess="python index.py"

# To use CGI headers:
# ENV cgi_headers="true"

# To change the mode to HTTP:
# ENV mode="http"

# To change the upstream URL:
# ENV upstream_url="http://127.0.0.1:8000"

# To enable debug writes:
# ENV write_debug="false"

# To set a custom health check:
# HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1

# Uncomment the following line to set a custom command
# CMD ["fwatchdog"]